// SPDX-FileCopyrightText: 2026 PCBoo contributors
// SPDX-License-Identifier: MIT
import { Braces, FileJson2, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { PageHeading } from "../components/shell";
import { Badge, Card, CardBody, CardHeader, EmptyState } from "../components/ui";
import { elementHumanLabel, elementId, titleCase } from "../lib/utils";
import type { CircuitElement, WorkspaceData } from "../types";

export function ExplorerPage({ data }: { data: WorkspaceData }) {
  const [query, setQuery] = useState("");
  const [type, setType] = useState("all");
  const [selected, setSelected] = useState<CircuitElement | null>(null);
  const types = useMemo(() => [...new Set(data.circuit.elements.map(({ type }) => type))].sort(), [data.circuit.elements]);
  const shown = useMemo(() => data.circuit.elements.filter((element) => (type === "all" || element.type === type) && (!query || JSON.stringify(element).toLowerCase().includes(query.toLowerCase()))).slice(0, 300), [data.circuit.elements, type, query]);
  return <><PageHeading eyebrow="Authoritative representation" title="Circuit data" description="Search and inspect the Circuit JSON generated from project source. This structured representation—not the browser—is authoritative." actions={<Badge tone="info"><Braces size={12} className="mr-1" /> {data.circuit.elements.length} elements</Badge>} />
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_26rem]"><Card className="min-w-0"><CardHeader className="flex-wrap items-center"><div className="flex h-9 min-w-56 flex-1 items-center gap-2 rounded-full border border-white/15 bg-[#191919] px-3 focus-within:border-orange-400"><Search size={14} className="text-[#817a72]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search IDs, names, nets, values…" className="w-full bg-transparent text-sm text-slate-200 outline-none placeholder:text-[#6f6962]" /></div><select value={type} onChange={(event) => setType(event.target.value)} className="h-9 rounded-full border border-white/15 bg-[#191919] px-3 text-xs font-bold text-slate-300 outline-none focus:border-orange-400"><option value="all">All types</option>{types.map((value) => <option key={value} value={value}>{value}</option>)}</select></CardHeader><div className="max-h-[68vh] overflow-auto">{shown.length === 0 ? <div className="p-5"><EmptyState icon={<FileJson2 size={21} />} title="No matching elements" description="Change the search text or type filter." /></div> : <table className="w-full text-left text-xs"><thead className="sticky top-0 bg-[#191919] text-[#817a72]"><tr><th className="px-4 py-2.5 font-black uppercase tracking-wide">Type</th><th className="px-4 py-2.5 font-black uppercase tracking-wide">Identifier</th><th className="hidden px-4 py-2.5 font-black uppercase tracking-wide sm:table-cell">Reference / description</th></tr></thead><tbody className="divide-y divide-white/10">{shown.map((element, index) => <tr key={elementId(element) ?? `${element.type}-${index}`} className="cursor-pointer hover:bg-orange-400/5" onClick={() => setSelected(element)}><td className="px-4 py-3 text-slate-300">{titleCase(element.type)}</td><td className="max-w-52 truncate px-4 py-3 font-mono text-slate-500">{elementId(element) ?? "—"}</td><td className="hidden max-w-72 truncate px-4 py-3 text-slate-500 sm:table-cell">{elementHumanLabel(element) ?? "—"}</td></tr>)}</tbody></table>}</div>{data.circuit.elements.length > 300 && <div className="border-t border-white/10 px-4 py-2 font-serif text-[11px] text-[#817a72]">Showing at most 300 browser rows. Use the structured inspection API for exhaustive agent queries.</div>}</Card>
      <Card className="h-fit overflow-hidden"><CardHeader><h2 className="text-sm font-semibold text-white">Element inspector</h2>{selected && <Badge tone="neutral">{selected.type}</Badge>}</CardHeader>{selected ? <pre className="max-h-[68vh] overflow-auto p-4 text-[11px] leading-5 text-slate-400">{JSON.stringify(selected, null, 2)}</pre> : <CardBody><EmptyState icon={<Braces size={21} />} title="Nothing selected" description="Select a row to inspect its complete structured record." /></CardBody>}</Card></div>
  </>;
}
