// SPDX-FileCopyrightText: 2026 Fulmetry contributors
// SPDX-License-Identifier: MIT
import { Archive, Factory, FileOutput, PackageCheck } from "lucide-react";
import type { ActionKind, WorkspaceData } from "../types";
import { PageHeading } from "../components/shell";
import { Badge, Button, Card, CardBody, CardHeader, EmptyState, JsonDetails } from "../components/ui";
import { titleCase } from "../lib/utils";

export function ManufacturingPage({ data, running, onRun }: { data: WorkspaceData; running: ActionKind | null; onRun: (kind: ActionKind) => Promise<void> }) {
  return <><PageHeading eyebrow="Fabrication handoff" title="Manufacturing" description="Review generated outputs and their evidence freshness. Fulmetry reports artifact references without exposing arbitrary project files." actions={<div className="flex gap-2"><Button variant="secondary" disabled={running !== null || !data.project.server.actionsEnabled} onClick={() => void onRun("build")}><Archive size={15} /> Build outputs</Button><Button disabled={running !== null || !data.project.server.actionsEnabled} onClick={() => void onRun("export-kicad")}><Factory size={15} /> Export KiCad</Button></div>} />
    <div className="grid gap-3 sm:grid-cols-3"><Card><CardBody><p className="text-xs font-black uppercase tracking-wide text-[#938d85]">Fabrication status</p><div className="mt-3 flex items-center justify-between"><span className="text-lg font-black text-white">{data.checks.statuses.fabrication?.state ?? "unknown"}</span><PackageCheck size={20} className="text-orange-300" /></div></CardBody></Card><Card><CardBody><p className="text-xs font-black uppercase tracking-wide text-[#938d85]">Evidence</p><div className="mt-3 flex items-center justify-between"><span className="text-lg font-black text-white">{data.artifacts.evidence.state}</span><Badge tone={data.artifacts.evidence.state === "current" ? "success" : data.artifacts.evidence.state === "stale" ? "danger" : "neutral"}>{data.artifacts.evidence.state}</Badge></div></CardBody></Card><Card><CardBody><p className="text-xs font-black uppercase tracking-wide text-[#938d85]">Output directory</p><code className="mt-3 block truncate text-sm text-slate-200">{data.artifacts.outputDirectory}</code></CardBody></Card></div>
    <Card className="mt-5"><CardHeader><div><h2 className="font-semibold text-white">Generated artifacts</h2><p className="mt-1 text-xs text-slate-500">Snapshot-bound references; files are not served by this interface.</p></div><Badge tone="neutral">{data.artifacts.artifacts.length}</Badge></CardHeader><CardBody>{data.artifacts.artifacts.length === 0 ? <EmptyState icon={<FileOutput size={22} />} title="No current artifacts" description="Build the project to generate manufacturing and verification outputs." /> : <div className="divide-y divide-slate-800">{data.artifacts.artifacts.map((artifact, index) => <div key={`${artifact.path}-${index}`} className="flex flex-col gap-2 py-3 first:pt-0 last:pb-0 sm:flex-row sm:items-center"><div className="rounded-lg bg-slate-800 p-2 text-slate-400"><FileOutput size={16} /></div><div className="min-w-0 flex-1"><p className="text-sm font-medium text-slate-200">{titleCase(artifact.kind)}</p><code className="block truncate text-xs text-slate-600">{artifact.path}</code></div></div>)}</div>}</CardBody></Card>
    <div className="mt-5"><JsonDetails label="Manufacturing evidence record" value={data.artifacts} /></div>
  </>;
}
