// SPDX-FileCopyrightText: 2026 PCBoo contributors
// SPDX-License-Identifier: MIT
import { Activity, FlaskConical, Play, Waves } from "lucide-react";
import type { ActionKind, WorkspaceData } from "../types";
import { AppLink, PageHeading } from "../components/shell";
import { Badge, Button, Card, CardBody, CardHeader, EmptyState, JsonDetails } from "../components/ui";

export function SimulationsPage({ data, selectedName, running, onRun }: { data: WorkspaceData; selectedName?: string | undefined; running: ActionKind | null; onRun: (kind: ActionKind, name?: string) => Promise<void> }) {
  const selected = data.simulations.simulations.find(({ name }) => name === selectedName) ?? data.simulations.simulations[0];
  return <><PageHeading eyebrow="Functional validation" title="Simulations" description="Run named testbenches and retain their status, diagnostics, and outputs only while they match the live project snapshot." actions={selected && <Button disabled={running !== null || !data.project.server.actionsEnabled} onClick={() => void onRun("simulate", selected.name)}>{running === "simulate" ? <Activity className="animate-spin" size={15} /> : <Play size={15} />} Run {selected.name}</Button>} />
    {data.simulations.simulations.length === 0 ? <EmptyState icon={<FlaskConical size={22} />} title="No simulations defined" description="Add a named testbench under the project simulations directory to make it available here." /> : <div className="grid gap-5 lg:grid-cols-[17rem_minmax(0,1fr)]"><Card className="h-fit"><CardHeader><h2 className="text-sm font-black uppercase tracking-wide text-white">Testbenches</h2><Badge tone="neutral">{data.simulations.simulations.length}</Badge></CardHeader><div className="p-2">{data.simulations.simulations.map((simulation) => <AppLink key={simulation.name} href={`/simulations/${encodeURIComponent(simulation.name)}`} className={`mb-1 flex items-center gap-3 rounded-lg border-l-4 px-3 py-2.5 text-sm font-bold ${selected?.name === simulation.name ? "border-orange-400 bg-orange-400/10 text-orange-200" : "border-transparent text-slate-400 hover:bg-white/5"}`}><Waves size={15} /><span className="truncate">{simulation.name}</span><span className={`ml-auto size-2 rounded-full ${simulation.freshness === "current" ? "bg-emerald-400" : simulation.freshness === "stale" ? "bg-rose-400" : "bg-slate-600"}`} /></AppLink>)}</div></Card>
      {selected && <div className="space-y-5"><Card><CardHeader><div><h2 className="font-semibold text-white">{selected.name}</h2><p className="mt-1 text-xs text-slate-500">{selected.elementCount} simulation elements</p></div><Badge tone={selected.freshness === "current" ? "success" : selected.freshness === "stale" ? "danger" : "neutral"}>{selected.freshness}</Badge></CardHeader><CardBody className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-[#191919] p-4"><p className="text-xs text-slate-600">Status</p><p className="mt-2 text-sm font-medium text-slate-200">{selected.status?.state ?? "not run"}</p></div><div className="rounded-xl bg-[#191919] p-4"><p className="text-xs text-slate-600">Diagnostics</p><p className="mt-2 text-sm font-medium text-slate-200">{selected.diagnostics.length}</p></div><div className="rounded-xl bg-[#191919] p-4"><p className="text-xs text-slate-600">Artifacts</p><p className="mt-2 text-sm font-medium text-slate-200">{selected.artifacts.length}</p></div></CardBody></Card><JsonDetails label="Simulation evidence" value={selected} /></div>}
    </div>}
  </>;
}
