# SPDX-FileCopyrightText: 2026 Fulmetry contributors
# SPDX-License-Identifier: MIT
# Intentionally empty. Security-sensitive child resolvers select this file so
# consumer-controlled bunfig.toml preloads and macros are never inherited.
